const { ROLE } = require("./serverConstants");

const REGISTRATION_CONFIG = {
  GOOGLE_REG_DOMAIN: process.env.CLIENT_DOMAIN,
  SYSADMIN_ALLOWED_REG_ROLES: [ROLE.ADMIN, ROLE.COUNSELOR, ROLE.SYS_ADMIN],
  ADMIN_ALLOWED_REG_ROLES: [ROLE.COUNSELOR],
};

module.exports = { REGISTRATION_CONFIG };
