const PERMISSIONS = {
  SUPER: 1,

  CREATE_ACCOUNT: 2,
  CREATE_COUNSELOR: 3,
  CREATE_CLIENTS: 4,

  GET_CLIENTS: 5,
  GET_COUNSELORS: 6,

  ASSIGN_ROLE: 8,
  CREATE_ROLE: 9,
  ASSIGN_PERMISSIONS: 10,

  UPDATE_PASSWORD: 11,
  SET_PERMISSION: 12,

  GET_COURSES: 13,
  GET_ACCOUNTS: 14,
  GET_PERMISSIONS: 15,
  GET_ACCOUNT_PERMISSIONS: 16,

  REQUEST_COUNSELING: 17,
  SET_PROFILE: 18,
  GET_ANNOUNCEMENT: 19,

  ASSIGN_COUNSELOR: 20,
  ACCEPT_CASE: 21,
  GET_CASE: 22,

  CREATE_SESSION: 23,
  GET_ASSIGNMENTS: 24,
  GET_SESSION: 25,

  GET_REQUEST: 26,
  GET_SELF_REQUEST: 27,
  GET_ROLE: 28,
  ARCHIVE_ACCOUNT: 29,
  REJECT_CASE: 30,
  GET_CASES: 31,
  GET_SESSIONS: 32,
  CREATE_VIRTUAL_ROOM: 33,
  GET_VIRTUAL_ROOM: 34,
  CREATE_COURSE: 35,
  UPDATE_COURSE: 36,
  GET_ACCOUNT: 37,
  CREATE_COUNSELING_QUESTION: 38,
  UPDATE_COUNSELING_QUESTION: 39,
  GET_COUNSELING_QUESTIONS: 40,
  GET_COUNSELING_QUESTIONAIRE: 41,
  ACCEPT_AVAILABLE_REQUEST: 42,
  GET_AVAILABLE_REQUESTS: 43,
  GET_APPOINTMENT_CASE: 44,
  UPDATE_ACCOUNT: 45,
  GET_AUDIT_LOGS: 46,
  UPDATE_COUNSELOR_ACCOUNT: 47,
  GET_COUNSELOR_ACCOUNT: 48,
  UPDATE_CASE: 49,
  UPDATE_VIRTUAL_ROOM: 50,
  GET_INTAKE_FORM: 51,
  UPDATE_SESSION: 52,
  GET_GENERATED_CASE_REPORT: 53,
  GET_CASE_FOR_MONITORING: 54,
  GET_CASE_RECORDS: 55,
  UPDATE_DEPARTMENTS: 56,
  GET_DEPARTMENTS: 57,
  UPDATE_ACCOUNT_INFORMATIONS: 58,
  GET_REFERRALS: 59,
  ACCEPT_REFERRALS: 60,
  UPDATE_REFERRALS: 61,
  GET_ANALYTICS: 62,
  CREATE_ANNOUNCEMENT: 63,
  UPDATE_ANNOUNCEMENT: 64
};

module.exports = {
  PERMISSIONS
}
